import { CustomOption } from "models/baseModels";
import { OrderDTO } from "models/orders";
import { COLORS } from "styles";

export const genderOptions: CustomOption[] = [
  { title: "Male", value: 0 },
  { title: "Female", value: 1 },
];

export const testOptions: CustomOption[] = [
  {
    title: "Favorite",
    value: 0,
    icon: "starOutlined",
    checkedIcon: "star",
    iconColor: "#f2ac85",
    checkedIconColor: "#f2ac85",
    disableRipple: true,
  },
  { title: "Bookmark", value: 1, icon: "bookmarkOutlined", checkedIcon: "bookmark", disableRipple: true },
  { title: "Normal", value: 2 },
];

export const orderStatusList: CustomOption[] = [
  { title: "Pending", value: "PENDING" },
  { title: "Preparing", value: "PREPARING" },
  { title: "On the way", value: "ON_THE_WAY" },
  { title: "Completed", value: "COMPLETED" },
  { title: "Cancelled", value: "CANCELLED" },
];

export const orderList: OrderDTO[] = [
  {
    id: "5BLIRI9RZH",
    customerName: "Trần Bảo Long",
    phoneNumber: "+84564243269",
    total: "270.000đ",
    createdDate: new Date(),
    status: "Pending",
    statusColor: COLORS.primary,
    statusBackgroundColor: COLORS.primaryBackground,
  },
  {
    id: "KTBUEHU2FI",
    customerName: "Võ Thanh Vũ",
    phoneNumber: "+84555562671",
    total: "300.000đ",
    createdDate: new Date(),
    status: "Pending",
    statusColor: COLORS.primary,
    statusBackgroundColor: COLORS.primaryBackground,
  },
  {
    id: "3J3S2CDF61",
    customerName: "Ngô Bích Hà",
    phoneNumber: "+84355571387",
    total: "120.000đ",
    createdDate: new Date(),
    status: "Preparing",
    statusColor: COLORS.orange,
    statusBackgroundColor: COLORS.orangeBackground,
  },
  {
    id: "K8S63YIN77",
    customerName: "Lê Nhã Hương",
    phoneNumber: "+84355542737",
    total: "50.000đ",
    createdDate: new Date(),
    status: "On the way",
    statusColor: COLORS.blue,
    statusBackgroundColor: COLORS.blueBackground,
  },
  {
    id: "1E4JAOCISC",
    customerName: "Lương Quốc Mạnh",
    phoneNumber: "+84855571621",
    total: "1.398.000đ",
    createdDate: new Date(),
    status: "Completed",
    statusColor: COLORS.green,
    statusBackgroundColor: COLORS.greenBackground,
  },
  {
    id: "V7OL6C3DCU",
    customerName: "Nguyễn Trọng Dũng",
    phoneNumber: "+84555511395",
    total: "936.500đ",
    createdDate: new Date(),
    status: "Completed",
    statusColor: COLORS.green,
    statusBackgroundColor: COLORS.greenBackground,
  },
  {
    id: "ZQ84510D2C",
    customerName: "Vũ Thanh Ngân",
    phoneNumber: "+84555546989",
    total: "492.000đ",
    createdDate: new Date(),
    status: "Cancelled",
    statusColor: COLORS.red,
    statusBackgroundColor: COLORS.redBackground,
  },
  {
    id: "SJO8SJ2O09",
    customerName: "Hoàng Ngọc Loan",
    phoneNumber: "+84210192830",
    total: "275.000đ",
    createdDate: new Date(),
    status: "On the way",
    statusColor: COLORS.blue,
    statusBackgroundColor: COLORS.blueBackground,
  },
  {
    id: "5BLIRI9RZH",
    customerName: "Trần Bảo Long",
    phoneNumber: "+84564243269",
    total: "270.000đ",
    createdDate: new Date(),
    status: "Pending",
    statusColor: COLORS.primary,
    statusBackgroundColor: COLORS.primaryBackground,
  },
  {
    id: "KTBUEHU2FI",
    customerName: "Võ Thanh Vũ",
    phoneNumber: "+84555562671",
    total: "300.000đ",
    createdDate: new Date(),
    status: "Pending",
    statusColor: COLORS.primary,
    statusBackgroundColor: COLORS.primaryBackground,
  },
  {
    id: "3J3S2CDF61",
    customerName: "Ngô Bích Hà",
    phoneNumber: "+84355571387",
    total: "120.000đ",
    createdDate: new Date(),
    status: "Preparing",
    statusColor: COLORS.orange,
    statusBackgroundColor: COLORS.orangeBackground,
  },
  {
    id: "K8S63YIN77",
    customerName: "Lê Nhã Hương",
    phoneNumber: "+84355542737",
    total: "50.000đ",
    createdDate: new Date(),
    status: "On the way",
    statusColor: COLORS.blue,
    statusBackgroundColor: COLORS.blueBackground,
  },
  {
    id: "1E4JAOCISC",
    customerName: "Lương Quốc Mạnh",
    phoneNumber: "+84855571621",
    total: "1.398.000đ",
    createdDate: new Date(),
    status: "Completed",
    statusColor: COLORS.green,
    statusBackgroundColor: COLORS.greenBackground,
  },
  {
    id: "V7OL6C3DCU",
    customerName: "Nguyễn Trọng Dũng",
    phoneNumber: "+84555511395",
    total: "936.500đ",
    createdDate: new Date(),
    status: "Completed",
    statusColor: COLORS.green,
    statusBackgroundColor: COLORS.greenBackground,
  },
];
