import { ProductTypeDTO } from "models/product";

export const productTypesEng: ProductTypeDTO[] = [
  {
    name: "Automotive",
    color: "",
    backgroundColor: "",
    children: ["Auto Parts", "Tires", "Companies with Auto Services"],
  } as ProductTypeDTO,
  {
    name: "Baby & Toddler",
    color: "",
    backgroundColor: "",
    children: ["Baby Furniture", "Baby Gear", "Baby Care & Safety"],
  } as ProductTypeDTO,
  {
    name: "Clothing & Shoes",
    color: "",
    backgroundColor: "",
    children: [
      "Baby Clothing",
      "Shoes",
      "Jewelry",
      "Watches",
      "Clothing Accessories",
      "Costumes",
      "Kids' Clothing",
      "Women's Clothing",
      "Men's Clothing",
      "Handbags",
      "Uniforms & Scrubs",
      "Teen Clothing",
    ],
  } as ProductTypeDTO,
  {
    name: "Computers",
    color: "",
    backgroundColor: "",
    children: [
      "Laptops",
      "Desktop Computers",
      "Monitors",
      "Laptop Bags",
      "Hardware & Peripherals",
      "Computer Networking",
      "Printers & Office Electronics",
      "Tablets",
    ],
  } as ProductTypeDTO,
  {
    name: "Electronics",
    color: "",
    backgroundColor: "",
    children: [
      "Video Games & Consoles",
      "Cameras & Camcorders",
      "Televisions",
      "MP3 & Media Players",
      "Home Theater",
      "Car Electronics",
      "Electronics Accessories",
      "Gadgets",
      "Cell Phone Accessories",
      "Headphones",
      "Smartwatches",
    ],
  } as ProductTypeDTO,
  {
    name: "Entertainment & Arts",
    color: "",
    backgroundColor: "",
    children: [
      "Tickets",
      "Media",
      "Collectibles",
      "Toys & Games",
      "Crafts & Fabrics",
      "Musical Instruments",
      "Party & Event Supplies",
      "Sheet Music",
      "Art Piece",
    ],
  } as ProductTypeDTO,
  {
    name: "Food & Gifts",
    color: "",
    backgroundColor: "",
    children: [
      "Specialty Food",
      "Flower Delivery",
      "Personalized Gifts",
      "Stationery & Cards",
      "Photo Gifts & Prints",
      "Gift Cards",
      "Gift Baskets",
      "Food Storage",
      "Beverages",
      "Special Diet",
      "Meat & Seafood",
      "Cheese",
      "Desserts & Sweets",
      "Packaged Meals & Snacks",
      "Popcorn",
      "Convenience Stores",
      "Novelty Gifts",
      "Fruit Gifts",
    ],
  } as ProductTypeDTO,
  {
    name: "Health & Beauty",
    color: "",
    backgroundColor: "",
    children: [
      "Personal Care",
      "Cosmetics",
      "Supplements",
      "Hair Care",
      "Fragrances",
      "Skin Care",
      "Dental Care",
      "Medical Supplies",
      "Men's Grooming",
      "Vision Care",
    ],
  } as ProductTypeDTO,
  {
    name: "Home & Garden",
    color: "",
    backgroundColor: "",
    children: [
      "Pet Supplies & Products",
      "Luggage",
      "Furniture",
      "Appliances",
      "Bed & Bath",
      "Home Decor",
      "Tools & Accessories",
      "Storage & Organization",
      "Vacuums & Cleaning Products",
      "Cookware & Cutlery",
      "Tableware",
      "Small Appliances",
      "Plants & Gardening",
      "Pools & Supplies",
      "Blinds",
      "Home Improvement",
    ],
  } as ProductTypeDTO,
  {
    name: "Office & Professional Services",
    color: "",
    backgroundColor: "",
    children: [
      "Office Supplies",
      "Office Furniture",
      "Ink & Toner",
      "Business Cards & Printing",
      "School Supplies",
      "Marketing & PR",
      "Legal Services",
      "Web Hosting & Tools",
      "Restaurant Supplies",
      "Stock Images & Videos",
      "Custom Printing",
    ],
  } as ProductTypeDTO,
  {
    name: "Personal & Home Services",
    color: "",
    backgroundColor: "",
    children: [
      "Financial Services",
      "Dating",
      "Personal Legal Services",
      "Tutoring & Test Prep",
      "Sitters & Nannies",
      "People Search",
      "Home Services",
      "Weight Loss Plans",
      "Meal Delivery",
    ],
  } as ProductTypeDTO,
  {
    name: "Restaurants & Dining",
    color: "",
    backgroundColor: "",
    children: ["Fast Food", "Italian", "Steak", "Seafood", "Breakfast", "Mexican", "Bar & Grill"],
  } as ProductTypeDTO,
  {
    name: "Software",
    color: "",
    backgroundColor: "",
    children: [
      "Tax Preparation",
      "Maintenance & Utilities",
      "Web Design & Development",
      "Graphics & Photo Editing",
      "Audio & Video Editing",
      "Personal Finance",
      "Productivity",
      "Antivirus & Security",
      "Education",
    ],
  } as ProductTypeDTO,
  {
    name: "Sports & Outdoors",
    color: "",
    backgroundColor: "",
    children: [
      "Outdoor Recreation",
      "Sportswear & Gear",
      "Indoor Games & Recreation",
      "Team Apparel & Merchandise",
      "Golf",
      "Team Sports Equipment",
      "Water Sports",
      "Winter Sports",
      "Fitness",
      "Billiards",
    ],
  } as ProductTypeDTO,
  {
    name: "Travel",
    color: "",
    backgroundColor: "",
    children: [
      "Flights",
      "Flights",
      "Rental",
      "Cruises",
      "Vacation Packages",
      "Resorts",
      "Rail & Car Services",
      "Travel Services",
      "Vacation Homes",
    ],
  } as ProductTypeDTO,
];

export const productTypesVi: ProductTypeDTO[] = [
  {
    name: "Ô tô",
    color: "",
    backgroundColor: "",
    children: ["Phụ tùng ô tô", "Bánh xe", "Dịch vụ chăm sóc ô tô"],
  } as ProductTypeDTO,
  {
    name: "Trẻ em",
    color: "",
    backgroundColor: "",
    children: ["Nội thất sơ sinh", "Phụ kiện sơ sinh", "Chăm sóc sức khỏe trẻ em"],
  } as ProductTypeDTO,
  {
    name: "Quần áo & Giày dép",
    color: "",
    backgroundColor: "",
    children: [
      "Quần áo sơ sinh",
      "Giày",
      "Trang sức",
      "Đồng hồ",
      "Phụ kiện thời trang",
      "Trang phục hóa trang",
      "Thời trang trẻ em",
      "Thời trang nữ",
      "Thời trang nam",
      "Túi xách",
      "Đồng phục",
      "Thời trang teen",
    ],
  } as ProductTypeDTO,
  {
    name: "Máy tính",
    color: "",
    backgroundColor: "",
    children: [
      "Máy tính xách tay",
      "Máy tính để bàn",
      "Màn hình",
      "Túi đựng laptop",
      "Phần cứng & linh kiện ngoại vi",
      "Thiết bị mạng",
      "Máy in và thiết bị văn phòng",
      "Máy tính bảng",
    ],
  } as ProductTypeDTO,
  {
    name: "Thiết bị điện tử",
    color: "",
    backgroundColor: "",
    children: [
      "Máy game & đĩa game",
      "Máy quay phim & máy ảnh",
      "TV",
      "Máy nghe nhạc",
      "Máy chiếu tại nhà",
      "Đồ chơi ô tô",
      "Phụ kiện điện tử",
      "Đồ chơi điện tử",
      "Phụ kiện điện thoại",
      "Tai nghe",
      "Đồng hồ thông minh",
    ],
  } as ProductTypeDTO,
  {
    name: "Giải trí & Nghệ thuật",
    color: "",
    backgroundColor: "",
    children: [
      "Vé",
      "Truyền thông",
      "Đồ sưu tập",
      "Đồ chơi",
      "Đồ thủ công",
      "Nhạc cụ",
      "Trang trí tiệc",
      "Bản nhạc",
      "Tác phẩm tranh",
    ],
  } as ProductTypeDTO,
  {
    name: "Thực phẩm & Quà tặng",
    color: "",
    backgroundColor: "",
    children: [
      "Đặc sản",
      "Hoa",
      "Quà handmade",
      "Dụng cụ văn phòng & thiệp",
      "Khung tranh",
      "Thẻ quà tặng",
      "Giỏ quà",
      "Hộp chứa thực phẩm",
      "Thức uống",
      "Đồ ăn kiêng",
      "Thịt và hải sản",
      "Phô mai",
      "Tráng miệng & kẹo",
      "Đồ ăn đóng hộp & bim bim",
      "Bắp rang",
      "Cửa hàng tiện lợi",
      "Quà độc đáo",
      "Giỏ trái cây",
    ],
  } as ProductTypeDTO,
  {
    name: "Sức khỏe & Chăm sóc sắc đẹp",
    color: "",
    backgroundColor: "",
    children: [
      "Chăm sóc cá nhân",
      "Mỹ phẩm",
      "Thực phẩm chức năng",
      "Chăm sóc tóc",
      "Nước hoa",
      "Chăm sóc da",
      "Chăm sóc răng",
      "Dụng cụ y tế",
      "Dụng cụ cắt tỉa nam",
      "Chăm sóc mắt",
    ],
  } as ProductTypeDTO,
  {
    name: "Nhà cửa & Sân vườn",
    color: "",
    backgroundColor: "",
    children: [
      "Sản phẩm cho thú cưng",
      "Vali",
      "Nội thất",
      "Đồ gia dụng",
      "Giường & bồn tắm",
      "Trang trí nhà",
      "Dụng cụ trang trí nhà",
      "Dụng cụ sắp xếp và lưu trữ trong nhà",
      "Máy hút bụi & sản phẩm làm sạch nhà",
      "Dụng cụ nấu nướng & dụng cụ bàn ăn",
      "Dụng cụ trang trí bàn",
      "Đồ dùng nhỏ",
      "Cây và dụng cụ làm vườn",
      "Dụng cụ hồ bơi",
      "Rèm cửa",
      "Dụng cụ sửa nhà",
    ],
  } as ProductTypeDTO,
  {
    name: "Văn phòng",
    color: "",
    backgroundColor: "",
    children: [
      "Dụng cụ văn phòng",
      "Nội thất văn phòng",
      "Mực in",
      "Danh thiếp",
      "Dụng cụ học tập",
      "Marketing",
      "Dịch vụ pháp lý",
      "Dịch vụ máy chủ web",
      "Dụng cụ nhà hàng",
      "Ảnh thiết kế có sẵn",
      "In theo yêu cầu",
    ],
  } as ProductTypeDTO,
  {
    name: "Dịch vụ tận nhà",
    color: "",
    backgroundColor: "",
    children: [
      "Dịch vụ tài chính",
      "Dịch vụ hẹn hò",
      "Dịch vụ pháp lý cá nhân",
      "Dịch vụ gia sư",
      "Dịch vụ trông trẻ",
      "Dịch vụ tìm người",
      "Dịch vụ lau dọn nhà",
      "Tư vấn giảm cân",
      "Giao đồ ăn tận nơi",
    ],
  } as ProductTypeDTO,
  {
    name: "Nhà hàng",
    color: "",
    backgroundColor: "",
    children: [
      "Đồ ăn nhanh",
      "Thức ăn Ý",
      "Steak",
      "Hải sản",
      "Đồ ăn sáng",
      "Thức ăn Mexico",
      "Dụng cụ bar & đồ nướng",
    ],
  } as ProductTypeDTO,
  {
    name: "Phần mềm",
    color: "",
    backgroundColor: "",
    children: [
      "Hỗ trợ khai báo thuế",
      "Bảo trì & tiện ích",
      "Thiết kế & phát triển trang web",
      "Chỉnh sửa hình ảnh",
      "Chỉnh sửa phim & âm thanh",
      "Tài chính cá nhân",
      "Quản lý công việc",
      "Diệt vi rút",
      "Giáo dục",
    ],
  } as ProductTypeDTO,
  {
    name: "Thể thao & Ngoài trời",
    color: "",
    backgroundColor: "",
    children: [
      "Giải trí ngoài trời",
      "Đồ tập & dụng cụ tập luyện",
      "Giải trí trong nhà",
      "Đồ nhóm",
      "Gôn",
      "Dụng cụ thể thao đồng đội",
      "Dụng cụ thể thao dưới nước",
      "Dụng cụ thể thao mùa đông",
      "Thể hình",
      "Bida",
    ],
  } as ProductTypeDTO,
  {
    name: "Du lịch",
    color: "",
    backgroundColor: "",
    children: [
      "Vé máy bay",
      "Khách sạn",
      "Thuê xe",
      "Du thuyền",
      "Combo nghỉ dưỡng",
      "Resort",
      "Dịch vụ đưa đón",
      "Dịch vụ lữ hành",
      "Villa",
    ],
  } as ProductTypeDTO,
];
